name: Manual Build App Image From Template (Release)
run-name: Manual Build App Image for "${{ github.event.repository.name }}"

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Tag version to build image for"
        required: false
      enable_cve_checks:
        description: "Enable CVE checks during image build"
        required: false
        default: "true"
      skip_tag_check:
        description: "Skip tag existence check before building image"
        required: false
        default: "true"
jobs:
  build-image:
    uses: supervisely-ecosystem/workflows/.github/workflows/build_image_from_template.yml@master
    with:
      image_name: "${{ github.event.repository.name }}"
      tag_version: "${{ github.event.inputs.tag_version }}"
      dockerfile_template_path: "docker/Dockerfile.tmpl"
      cve_checks: "${{ github.event.inputs.enable_cve_checks }}"
      skip_tag_check: "${{ github.event.inputs.skip_tag_check }}"
